// src/components/Blog.vue
<template>
    <article id="blog" class="blog__container">
        <v-container fluid>
            <div class="text-center pb-12">
                <h2 class="text-h2 pb-4">Blog</h2>
                <p class="blog__intro text-center text-body">
                    Recently, I've started homelabbing to improve my DevOps and
                    infrastructure skillset. Going forward, I am to write about what I've learnt
                    for future reference and hopefully to help others as well. View my latest posts 
                    below, or go to 
                </p>
                <a class="blog__intro text-center text-body" href="https://blog.zakdowsett.co.uk/">https://blog.zakdowsett.co.uk/</a>
            </div>


            <v-row>
                <v-col v-for="item in posts" cols="12" md="4">
                    <BlogItem 
                        :key="item.id"
                        :title="item.title"
                        :extract="item.excerpt"
                        :link="item.url"
                        :image="item.feature_image"
                    />
                </v-col>
            </v-row>

        </v-container>
    </article>
</template>

<script setup>
import { ref } from 'vue';
import BlogItem from './BlogItem.vue';

const posts = ref([]);
fetch('https://blog.zakdowsett.co.uk/ghost/api/content/posts/?key=44a65805ff949082d0ff581ab1&include=tags&limit=3')
    .then(res => res.json())
    .then(data => posts.value = data.posts)

</script>

<style lang="scss" scoped>
.blog__container {
    min-height: 70vh;
    padding: 64px;
    .v-container {
        max-width: 100em;
        margin: 0 auto;
    }
}

@media only screen and (max-width: 600px) {
    .blog__container {
        padding: 64px 0;
    }
}

.blog__intro {
    max-width: 40em;
    margin: 0 auto;
}

.text-body {
    font-size: 1.2rem;
    padding-bottom: 1em;
}

.d-grid {
    display: grid;
    // grid-template-columns: 1fr 1fr;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
}

</style>

// src/components/home/blog.tsx
import React from "react"
import BlogItem from "./blog_item"
import { graphql, Link, useStaticQuery } from "gatsby"
import BlogMDX from "../../models/blog_mdx";

const Blog: React.FC = () => {
    const data = useStaticQuery(graphql`
      query {
        allMdx(
          filter: { fields: { collection: { eq: "blog"}}, frontmatter: { published: { eq: true }}},
          sort: { frontmatter: { date: DESC }},
          limit: 3
        ) {
          nodes {
            frontmatter {
              title
              subtitle
              hero_attr
              date(formatString: "DD MMM, YYYY")
              hero_img {
                childImageSharp {
                  gatsbyImageData
                }
              }
            }
            fields {
              slug
            }
            id
          }
        }
      }
      `);

    const posts = data.allMdx.nodes;
    return (
        <section id="blog" className="py-16 px-3 md:px-24  min-h-[90vh]">
            <div className="container max-w-[80em] mx-auto">

                <div className="text-center pb-12">
                    <h2 className="text-6xl pb-4 font-light">Blog</h2>
                    <p className="text-center text-xl">
                        Recently, I've started homelabbing to improve my DevOps and infrastructure skillset.
                        Going forward, I am to write about what I've learnt for future reference and hopefully to help others as well.
                        View my latest posts below, or go to
                    </p>
                    <Link to="/blog" className="text-xl pt-8">
                        https://zakdowsett.co.uk/blog
                    </Link>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {posts.map((item: BlogMDX) => (
                        <BlogItem 
                          key={item.id}
                          title={item.frontmatter.title}
                          excerpt={item.frontmatter.subtitle}
                          image={item.frontmatter.hero_img}
                          imageAlt={item.frontmatter.hero_attr}
                          link={item.fields.slug}
                          date={item.frontmatter.date}
                        />
                    ))}
                </div>

            </div>
        </section>
    );
}   

export default Blog;
