// src/components/portfolio_item.tsx
import { FC, ReactNode } from "react"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faArrowUpRightFromSquare } from "@fortawesome/free-solid-svg-icons"

interface ItemProps {
    name: string
    logo: string
    background: string
    link: string
    skills: string[]
    children: ReactNode[]
}

const PortfolioItem: FC<ItemProps> = ({ name, logo, background, link, skills, children }) => {
    return (
        <div className="grid grid-cols-12 grid-flow-roq gap-4">
            <a href={link} className="col-span-12 md:col-span-4 relative overflow-hidden rounded-lg h-[250px] shadow-xl">
                <img className="object-cover w-full h-full" src={background} alt={`${name} background`} />
                <div className="absolute top-0 grid w-full h-full bg-black/50">
                    <img className="max-h-[80px] max-w-[80%] place-self-center" src={logo} alt={`${name} logo`} />
                </div>
            </a>
            <div className="text-justify col-span-12 md:col-span-8 space-y-4">
                <a href={link} className="pb-2 space-x-2 hover:underline text-black dark:text-white">
                    <h3 className="text-3xl inline">{name}</h3>
                    <FontAwesomeIcon className="mb-4" icon={faArrowUpRightFromSquare} />
                </a>
                {children}
                <div className="flex flex-wrap">
                    {skills.map(skill => (
                        <div
                            key={skill}
                            className="d-inline-block mr-2 mb-2 p-2 bg-neutral-200 text-black rounded"
                        >{skill}</div>
                    ))}
                </div>
            </div>
        </div>
    );
}

export default PortfolioItem;

// src/components/PortfolioItem.vue
<template>
    <v-row class="mb-4">
        <v-col cols="4">
            <v-card height="250" :rounded="8">
                <v-img cover height="100%" :src="image" :alt="name">
                    <img class="central_logo" :src="logo" alt="">
                </v-img>
            </v-card>
        </v-col>
        <v-col>
            <a :href="link">
                <h3 class="text-h4 pb-2">{{name}}</h3>
            </a>
            <slot></slot>
            <div>
                <span
                    v-for="skill in skills"
                    :key="skill"
                    class="about__skillpill pa-2 mr-2 mb-2 reset_font"
                >{{ skill }}</span>
            </div>
        </v-col>
    </v-row>
</template>

<script setup>
const props = defineProps({
    name: String,
    image: String,
    link: String,
    logo: String,
    skills: Array
});
</script>

<style lang="scss" scoped>
.reset_font {
    font-size: 1rem;
}

.v-img :deep(.v-responsive__content) {
    display: grid;
    background: rgba(0,0,0,0.5)
}

.central_logo {
    max-height: 80px;
    max-width: 80%;
    place-self: center;
}
</style>
